class Fig2dev < Formula
  desc "Translates figures generated by xfig to other formats"
  homepage "https://mcj.sourceforge.io/"
  url "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.8a.tar.xz"
  sha256 "6336ac492d0f71dfb7a1dd8f4d78eae17aa57a34f743d4e5ba9814991c2da7ae"

  livecheck do
    url :stable
    regex(%r{url=.*?/fig2dev[._-]v?(\d+(?:\.\d+)+[a-z]?)\.t}i)
  end

  depends_on "ghostscript"
  depends_on "libpng"
  depends_on "netpbm"

  def install
    #inreplace "fig2dev/dev/genemf.h", "#include <endian.h>", "#include <machine/endian.h>" #Now corrected upstream

    args = %W[
      --prefix=#{prefix}
      --disable-dependency-tracking
      --disable-silent-rules
      --enable-transfig
    ]

    system "./configure", *args
    system "make", "install"

    # Install a fig file for testing
    # pkgshare.install "fig2dev/tests/data/patterns.fig"

    # Installs a directory of some useful samples (and used for testing)
    pkgshare.install "fig2dev/tests/data/"
  end

  test do
    system "#{bin}/fig2dev", "-L", "png", "#{pkgshare}/patterns.fig", "patterns.png"
    assert_predicate testpath/"patterns.png", :exist?, "Failed to create PNG"
  end
end
